"""Markdown method-card exporter for manual vendor transcription."""

from datetime import datetime, timezone
from importlib import metadata
from pathlib import Path
import re


def _read_package_version() -> str:
    """Read the package version from installed metadata or pyproject.toml."""
    repo_root = Path(__file__).resolve().parents[2]
    fallback_version = "0.1.0"
    try:
        pyproject = (repo_root / "pyproject.toml").read_text(encoding="utf-8")
    except OSError:
        pyproject = None

    if pyproject is not None:
        match = re.search(r'^version\s*=\s*"([^"]+)"', pyproject, re.MULTILINE)
        if match:
            return match.group(1)

    try:
        return metadata.version("oglycan-optimizer")
    except metadata.PackageNotFoundError:
        pass
    return fallback_version


def build_method_card(
    site_catalog: dict,
    params: dict,
    evaluation: dict,
) -> str:
    """Return a markdown method card for manual transcription into a vendor editor."""
    version = f"v{_read_package_version()}"

    glycoprotein = site_catalog.get("glycoprotein", {})
    enzyme = params.get("enzyme_preprocessing", {})
    lc = params.get("lc_gradient", {})
    frag = params.get("fragmentation", {})
    ms_acq = params.get("ms_acquisition", {})
    search = params.get("search_params", {})
    glycan_db = params.get("glycan_database", {})
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "# O-Glycan Method Card",
        "",
        f"Generated by oglycan-optimizer {version}",
        f"Timestamp (UTC): {timestamp}",
        "",
        "> Note: these values must be transcribed into the vendor method editor",
        "> (for example, Xcalibur for Thermo) by hand before acquisition.",
        "",
        "## Overview",
        f"- Glycoprotein: {glycoprotein.get('name', evaluation.get('molecule', 'unknown'))}",
        f"- O-glycosite count: {evaluation['total_sites']}",
        f"- Composite score: {evaluation['composite_score']:.4f}",
        f"- Sites localized: {evaluation['sites_localized']}/{evaluation['total_sites']}",
        f"- Localization threshold: {evaluation['localization_threshold']:.2f}",
        "",
        "| Breakdown | Score |",
        "| --- | ---: |",
    ]
    for key, value in evaluation["composite_breakdown"].items():
        lines.append(f"| {key.replace('_', ' ').title()} | {value:.4f} |")
    lines.extend(
        [
            "",
            "## Enzyme Prep",
            f"- Primary protease: {enzyme.get('primary', 'n/a')}",
            f"- Use SialEXO: {enzyme.get('use_sialexo', False)}",
            f"- Use PNGase F: {enzyme.get('use_pngasef', False)}",
            f"- Digestion time (h): {enzyme.get('digestion_time_hours', 'n/a')}",
            f"- Temperature (C): {enzyme.get('temperature_C', 'n/a')}",
            "",
            "## Chromatography",
            f"- Column: {lc.get('column', 'n/a')}",
            f"- Gradient: {lc.get('gradient_start_pct_b', 'n/a')} to {lc.get('gradient_end_pct_b', 'n/a')} %B over {lc.get('gradient_time_min', 'n/a')} min",
            f"- Flow rate (uL/min): {lc.get('flow_rate_uL_min', 'n/a')}",
            "",
            "## MS1",
            f"- Resolution MS1: {ms_acq.get('resolution_ms1', 'n/a')}",
            f"- AGC target MS1: {ms_acq.get('agc_target_ms1', 'n/a')}",
            f"- Max injection MS1 (ms): {ms_acq.get('max_injection_ms1', 'n/a')}",
            "",
            "## MS2 / Fragmentation",
            f"- Mode: {frag.get('mode', 'n/a')}",
            f"- EThcD supplemental activation (%): {frag.get('ethcd_sa_percent', 'n/a')}",
            f"- Collision energy NCE: {frag.get('collision_energy_nce', 'n/a')}",
            f"- Isolation window (m/z): {frag.get('isolation_window_mz', 'n/a')}",
            f"- Charge-state range: {frag.get('charge_state_min', 'n/a')} to {frag.get('charge_state_max', 'n/a')}",
            f"- Resolution MS2: {ms_acq.get('resolution_ms2', 'n/a')}",
            f"- AGC target MS2: {ms_acq.get('agc_target_ms2', 'n/a')}",
            f"- Max injection MS2 (ms): {ms_acq.get('max_injection_ms2', 'n/a')}",
            f"- Dynamic exclusion (s): {ms_acq.get('dynamic_exclusion_s', 'n/a')}",
            "",
            "## Search",
            f"- MS1 tolerance (ppm): {search.get('mass_tolerance_ms1_ppm', 'n/a')}",
            f"- MS2 tolerance (ppm): {search.get('mass_tolerance_ms2_ppm', 'n/a')}",
            f"- Min peptide length: {search.get('min_peptide_length', 'n/a')}",
            f"- Max missed cleavages: {search.get('max_missed_cleavages', 'n/a')}",
            f"- FDR threshold: {search.get('fdr_threshold', 'n/a')}",
            f"- Glycan database: core1={glycan_db.get('include_core1', False)}, core2={glycan_db.get('include_core2', False)}, core3={glycan_db.get('include_core3', False)}, sialylated={glycan_db.get('include_sialylated', False)}, fucosylated={glycan_db.get('include_fucosylated', False)}, max_size={glycan_db.get('max_glycan_size', 'n/a')}",
            "",
            "## Results",
            "| Site | Core Types | Difficulty | Confidence | Status |",
            "| --- | --- | ---: | ---: | --- |",
        ]
    )
    for row in evaluation["site_results"]:
        lines.append(
            f"| {row['amino_acid']}{row['position']} | {', '.join(row['core_types'])} | {row['difficulty']:.2f} | {row['confidence']:.4f} | {'PASS' if row['pass'] else 'FAIL'} |"
        )
    lines.extend(
        [
            "",
            "## Sub-model Scores",
            "| Model | Score |",
            "| --- | ---: |",
        ]
    )
    for key, value in evaluation["sub_model_scores"].items():
        lines.append(f"| {key.replace('_', ' ').title()} | {value:.4f} |")
    return "\n".join(lines) + "\n"
